package com.epam.aliebay.constant;

public class OtherConstants {
    public static final String LANGUAGE_EN = "en";
    public static final String REFERER_HEADER = "referer";
    public static final String SHOPPING_CART_COOCKIE = "cart";
    public static final int SHOPPING_CART_COOCKIE_AGE = 30*24*60;
    public static final String APPLICATION_JSON = "application/json";
    public static final String TOTAL_COUNT_JSON = "totalCount";
    public static final String TOTAL_COST_JSON = "totalCost";
    public static final String ORDER_STATUS_JSON = "orderStatus";
    public static final String ID_ORDER_STATUS_JSON = "idOrderStatus";
    public static final String USER_STATUS_JSON = "userStatus";
    public static final String PRICE_SORT_PARAMETER = "price";
    public static final String ID_SORT_PARAMETER ="id";
    public static final int COUNT_CATEGORIES_LEFT_PANEL_ON_HOME_PAGE = 9;
    public static final int COUNT_CATEGORIES_RIGHT_PANEL_ON_PRODUCT_PAGE = 5;
    public static final int COUNT_PRODUCERS_RIGHT_PANEL_ON_PRODUCT_PAGE = 5;
    public static final int COUNT_PRODUCTS_ON_PRODUCT_PAGE = 9;
    public static final String CUSTOMER_ROLE = "customer";
    public static final String ADMIN_ROLE = "admin";
    public static final String PREFIX_TO_SHOW_IMAGE_ON_HTML_PAGE = "data:image/png;base64,";
    public static final int LENGTH_OF_PREFIX_TO_SHOW_IMAGE_ON_HTML_PAGE = 22;
    public static final int ID_ORDER_STATUS_IN_PROCESS = 1;
    public static final int ID_ORDER_STATUS_CANCELLED = 4;
    public static final int ID_USER_STATUS_ACTIVE = 1;
    public static final int ID_USER_STATUS_BANNED = 2;
    public static final String UPDATE_TAB = "update";
    public static final String CHANGE_PASSWORD_TAB = "changePassword";
    public static final int INDEX_ONE_EDITED_CATEGORIES = 1;
    public static final String CHANGE_PRODUCT_FORM_ACTION = "change-product";
    public static final String ADD_PRODUCT_FORM_ACTION = "add-product";
    public static final String CHANGE_PRODUCER_FORM_ACTION = "change-producer";
    public static final String ADD_PRODUCER_FORM_ACTION = "add-producer";
    public static final String CHANGE_CATEGORY_FORM_ACTION = "change-category";
    public static final String ADD_CATEGORY_FORM_ACTION = "add-category";
    public static final String ERROR_403_TITLE = "error.403.title";
    public static final String ERROR_403_MESSAGE = "error.403.message";
    public static final String ERROR_401_TITLE = "error.401.title";
    public static final String ERROR_401_MESSAGE = "error.401.message";
    public static final String ERROR_400_TITLE_PRODUCT_NOT_ENOUGH = "error.400.title.not.enough";
    public static final String ERROR_400_MESSAGE_PRODUCT_NOT_ENOUGH = "error.400.message.not.enough";
    public static final int ID_PARENT_OF_HIGHEST_HIERARCHY_CATEGORY = 0;
    public static final String PATH_TO_DEFAULT_IMAGE = "/media/default_image.png";
}
